ODS PDF FILE = "C:\Documents\IDS 462 - SAS\Group Project\PROJECT_Q1_ALL_PLAYERS.PDF";
ODS rtf FILE = "C:\Documents\IDS 462 - SAS\Group Project\PROJECT_Q1_ALL_PLAYERS.rtf";

DATA SHOT_LOG;
INFILE 'C:\Documents\IDS 462 - SAS\Group Project\shot_logs.csv' DSD DLM = ',' FIRSTOBS=2 MISSOVER;
LENGTH CLOSEST_DEFENDER $25 PLAYER_NAME $25;
INPUT GAME_ID MATCHUP_DATE $ TEAM $ OPPOSITION_TEAM $ LOCATION $ RESULT $ FINAL_MARGIN SHOT_NUMBER PERIOD GAME_CLOCK $ SHOT_CLOCK DRIBBLES TOUCH_TIME SHOT_DIST PTS_TYPE SHOT_RESULT $ CLOSEST_DEFENDER $ CLOSEST_DEFENDER_PLAYER_ID CLOSE_DEF_DIST FGM PTS PLAYER_NAME $ PLAYER_ID;
*FORMAT SHOT_CLOCK miss_value_sc.;
IF SHOT_CLOCK = . THEN SHOT_CLOCK = 0;
GAME_CLOCK = TRANWRD(GAME_CLOCK, ":", ".");
GAME_CLOCK = INPUT(GAME_CLOCK, 5.2);
RUN;

DATA DUMMY_SHOT_LOG;
SET SHOT_LOG;
IF Period not=. then do;
Period_1 = (Period=1);
Period_2 = (Period=2);
Period_4 = (Period=4);
PTS_TYPE_2 = (PTS_TYPE=2);
SHOT_RESULT_MADE = (SHOT_RESULT="made");
LOCATION_HOME = (LOCATION = "H");
GAME_CLOCK_1 = INPUT(GAME_CLOCK, 5.2);
END;
RUN;

PROC LOGISTIC DATA = DUMMY_SHOT_LOG DESCENDING;
TITLE "LOGISTIC REGRESSION OUTPUT - ALL PLAYERS";
WHere Period IN(1,2,3,4);
MODEL SHOT_RESULT_MADE = LOCATION_HOME GAME_CLOCK_1 SHOT_CLOCK DRIBBLES TOUCH_TIME SHOT_DIST PTS_TYPE_2 CLOSE_DEF_DIST Period_1 Period_2 Period_4 ;
RUN;

ODS PDF CLOSE;


** Stephen Curry;

ODS PDF FILE = "C:\Documents\IDS 462 - SAS\Group Project\PROJECT_Q1_Filtered.PDF";

DATA SHOT_LOG;
INFILE 'C:\Documents\IDS 462 - SAS\Group Project\shot_logs.csv' DSD DLM = ',' FIRSTOBS=2 MISSOVER;
LENGTH CLOSEST_DEFENDER $25 PLAYER_NAME $25;
INPUT GAME_ID MATCHUP_DATE $ TEAM $ OPPOSITION_TEAM $ LOCATION $ RESULT $ FINAL_MARGIN SHOT_NUMBER PERIOD GAME_CLOCK $ SHOT_CLOCK DRIBBLES TOUCH_TIME SHOT_DIST PTS_TYPE SHOT_RESULT $ CLOSEST_DEFENDER $ CLOSEST_DEFENDER_PLAYER_ID CLOSE_DEF_DIST FGM PTS PLAYER_NAME $ PLAYER_ID;
*FORMAT SHOT_CLOCK miss_value_sc.;
IF SHOT_CLOCK = . THEN SHOT_CLOCK = 0;
GAME_CLOCK = TRANWRD(GAME_CLOCK, ":", ".");
GAME_CLOCK = INPUT(GAME_CLOCK, 5.2);
RUN;

DATA DUMMY_SHOT_LOG;
SET SHOT_LOG;
IF Period not=. then do;
Period_1 = (Period=1);
Period_2 = (Period=2);
Period_4 = (Period=4);
PTS_TYPE_2 = (PTS_TYPE=2);
SHOT_RESULT_MADE = (SHOT_RESULT="made");
LOCATION_HOME = (LOCATION = "H");
GAME_CLOCK_1 = INPUT(GAME_CLOCK, 5.2);
END;
RUN;

PROC LOGISTIC DATA = DUMMY_SHOT_LOG DESCENDING;
TITLE "LOGISTIC REGRESSION OUTPUT - STEPHEN CURRY";
WHere PLAYER_NAME = "stephen curry" AND Period IN(1,2,3,4);
MODEL SHOT_RESULT_MADE = LOCATION_HOME GAME_CLOCK_1 SHOT_CLOCK DRIBBLES TOUCH_TIME SHOT_DIST PTS_TYPE_2 CLOSE_DEF_DIST Period_1 Period_2 Period_4 ;
RUN;

ODS PDF CLOSE;
ODS rtf CLOSE;

